### ISSUE TITLE
Imagewallet review

### ISSUE THREAD

**Issue by retotrinkler** [Trinkler/imagewallet#11]
- [ ] Remove or make optional (default false) أبو يوسف يعقوب بن إسحاق الصبّاح الكندي && PYRAMID text
- [ ] https://github.com/Trinkler/imagewallet/blob/17926820b2cc5dd311a1efa147ea3369b82a503d/src/cryptography/keyDerivation.js#L80 requires a `0 byte` before `seed` to be compatible w standard. See https://github.com/nimiq-network/core/blob/1cd316f6e541277a281be55973a5cda1c7f1fed8/src/main/generic/consensus/base/primitive/ExtendedPrivateKey.js#L35
- [ ] Review comments of https://github.com/Trinkler/imagewallet/blob/17926820b2cc5dd311a1efa147ea3369b82a503d/src/cryptography/keyDerivation.js#L19 and https://github.com/Trinkler/imagewallet/blob/17926820b2cc5dd311a1efa147ea3369b82a503d/src/cryptography/keyDerivation.js#L43
- [ ] _Note_: It's important that `convert.hexToArray` returns 4 byte. Eg: https://github.com/Trinkler/imagewallet/blob/17926820b2cc5dd311a1efa147ea3369b82a503d/src/cryptography/keyDerivation.js#L80

**Comment by retotrinkler** [comment]
@qcortex has this been implemented?

**Comment by qcortex** [comment]
Removed
