### ISSUE TITLE
Use esm for es6 compatibility

### ISSUE THREAD

**Issue by retotrinkler** [Trinkler/imagewallet#15]
Please provide the following information:

### Expected behaviour

No error when using imagewallet as a dependency.

### Actual behaviour

Node packages dependent on imagewallet get the following error.

```
import decodeQR from './decoder/decodeQR';
^^^^^^

SyntaxError: Unexpected token import
```

### Information about our environment

See version 0.2.10 of imagewallet for last time esm support was enabled.

**Comment by takahser** [comment]
getting the same error also when using the @trinkler/imagewallet-tx npm package in agora-swap (but not when typescript is used, e.g. as in the imagewallet.io SPA)

**Comment by retotrinkler** [comment]
Maybe something like this works: https://github.com/paritytech/js-api/blob/master/package.json#L28

**Comment by retotrinkler** [comment]
A typescript version of it might be useful then; Closing it for now as not priority.

**Comment by takahser** [comment]
it seems to be this issue, which has no working solution: https://github.com/TypeStrong/ts-node/issues/617

**Comment by retotrinkler** [comment]
ok thanks @takahser - reopening - we should consider a typescript rewrite at some pt

**Comment by takahser** [comment]
@retotrinkler I thought, the migration could be a quick thing, so got started with it. Turns out, there are quite some changes necessary. I've pushed the wip, but let's continue on this after the agora release maybe:

https://github.com/Trinkler/imagewallet/tree/feature/migrate-to-typescript

**Comment by retotrinkler** [comment]
> This testing issue has a manual workaround.  This issue is caused by jest not handling es6 imports from node modules.  However if the package is imported locally then test will run.  Therefore one can overwrite the @trinkler/imagewallet import for ‘../../../imagewallet/src/index’ and then run tests.

**Comment by takahser** [comment]
@retotrinkler I tried importing `imagewallet` using `import * as ImageWallet from '../../../imagewallet/src/index'` but it still threw the same error

**Comment by takahser** [comment]
I finally found a solution to using **@trinkler/imagewallet** when using a TypeScript jest unit test that runs on the node platform.

1. install [esm](https://github.com/standard-things/esm): `npm i esm`
2. load the es module:

```TypeScript
require = require("esm")(module)
```
3. import **imagewallet** from using a relative path:

```TypeScript
// file: /test/some.spec.js
const imagewallet = require('../node_modules/@trinkler/imagewallet');
```

4. (only when using typescript) install the node types: `npm i @types/node -D`

**Comment by retotrinkler** [comment]
closing this as @takahser is sufficient for now
