### ISSUE TITLE
Bitcoin Key derivation different on Bitcore play wallet

### ISSUE THREAD

**Issue by retotrinkler** [Trinkler/imagewallet#27]
Please provide the following information:

Bitcoin private key as generated by [this](https://github.com/Trinkler/imagewallet/issues/26) wallet:
`00758e885663c026793e08a787053b4e891c1ad92b055c759c7707a2e82d296c`

Gives: https://www.blockchain.com/btc/address/17cREVtcYRCzwXzchKSkP1HmkzVaFvkLcd on imagewallet.io and 
`mn8NXYybMSeFieUEQtR8CvW6cz6HCVBc4T` on https://bitcore.io/playground/#/address

![image](https://user-images.githubusercontent.com/13721565/51987472-e2ce8d00-24a2-11e9-8d0e-6c06a997cefe.png)

### Expected behaviour

Same address

### Actual behaviour

Different address

### Information about our environment

* OS & Verison
* Browser & Version
* Parity version
* ... other helpful information

**Comment by retotrinkler** [comment]
relevant line of code is in imagewallet-tx repo https://github.com/Trinkler/imagewallet-tx/blob/master/src/wallet/btc-wallet.service.ts#L26-L29

@takahser do you know why there is a difference?

**Comment by takahser** [comment]
mn8NXYybMSeFieUEQtR8CvW6cz6HCVBc4T is a testnet address, 17cREVtcYRCzwXzchKSkP1HmkzVaFvkLcd is a main/prod net address

**Comment by takahser** [comment]
if you select **live net** the same address will show up

![image](https://user-images.githubusercontent.com/5393704/51989749-faf4db00-24a7-11e9-892e-22b34d293b42.png)

**Comment by retotrinkler** [comment]
great thanks.
also tested nim against https://nimiq-tools.github.io/tools/generate-address.html and looks fine
